import React from 'react';
import {
  StyleSheet,
  View,
  Image,
  Text,
  Button,
  AsyncStorage,
  ScrollView,
  RefreshControl,
  Platform
} from 'react-native';

import Ionicon from 'react-native-vector-icons/Ionicons'
//import Entypo from 'react-native-vector-icons/Entypo'

import brand from '../../../Styles/brand'

class Terms extends React.Component {

  // this is a child/nested screen in the SchedulesStack
  // Look at SchedulesStack for tricks with hiding the tabBar and hiding the back button title
  static navigationOptions = (navigate) => ({

    title: 'Terms & Conditions',

    // these seem to ONLY work here
    headerStyle: {backgroundColor: brand.colors.primary },
    headerTintColor: 'white',


  })




  render() {

    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>

      <ScrollView
            style={{ paddingBottom: 100 }}
          >


        <Text style={{ padding: 20 }}>

Terms & Conditions
 User Agreement
 Last Modified: January 9, 2015
 This User Agreement (“Agreement”) is between You and ROS Technology Services, Inc. DBA Rosnet (“Company”) for use of Rosnet (the “Service”).
 YOU SHOULD READ CAREFULLY AND UNDERSTAND THIS AGREEMENT. YOUR USE OF THE SERVICE AND/OR REGISTRATION AND VERIFICATION OF YOUR ACCOUNT FOR USE OF THE SERVICES, CONSTITUTES YOUR ONGOING ACCEPTANCE OF THIS AGREEMENT IN YOUR BEHALF AND IN BEHALF OF ANY OF YOUR EMPLOYEES AND AGENTS TO WHOM YOU PROVIDE THE SERVICE. YOU ARE SOLELY RESPONSIBLE AND LIABLE FOR YOUR NON-COMPLIANCE AND THE NON-COMPLIANCE OF YOUR EMPLOYEES OR AGENTS WITH THIS AGREEMENT. YOU FURTHER REPRESENT THAT YOU ARE AUTHORIZED TO ACCEPT THESE TERMS AND CONDITIONS. IF YOU CANNOT ACCEPT THIS AGREEMENT, PLEASE DO NOT USE THE SERVICE.
 1. Service
 Rosnet is a scheduling-related information and messaging service, available from the Company either online through our website at www.Rosnet.com or via mobile application. The Service provides users with the ability to store scheduling-related information into one location, share that information, and receive updates, manage availability, request time off, and message and receive messages from other employees regarding scheduling. Company has no obligation to provide support, maintenance, upgrades, modifications or new releases to the Service under this Agreement.
 2. Use of Service
 a. Company grants You a limited right to use the Service for personal, noncommercial and lawful purposes only.
 b. Restrictions. Except as expressly authorized by Company in writing or otherwise enabled by Company:
 i. You will not access the Service in a manner or through an interface not provided or authorized by Company including but not limited to, any automated means (e.g., scripts or bots);
 ii. You will not copy, reproduce, duplicate sell, trace, resell or exploit the Service;
 iii. You will not reverse engineer, disassemble or decompile any portion of the Service or its software, except to the extent expressly permitted by applicable law, and then only after You have notified Company in writing of Your intended activities;
 iv. You will not upload, transmit, post or otherwise share any content that violates or infringes upon the rights of any third party, including, without limitation, copyright, trademark, privacy, publicity or other personal or proprietary rights;
 v. You will not modify, adapt or hack the Service or modify a website so as to falsely imply that it is associated with the Services. You will not create or submit unwanted email or other messages to any other Service users;
 vi. You will not transmit any worms or viruses or any code of a destructive nature through Your access or use of the Service;
 vii. You will not use the Service to upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable.;
 viii. You will not use the Service to upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;
 ix. You will not republish or syndicate the information available on the Service (including but not limited to information made accessible to non-paying users via any portion of the Service provided on a paid subscription basis);
 x. You will not disrupt, overwhelm, attack, modify or interfere with the Service or its associated software, hardware and/or servers in any way, and You agree not to impede or interfere with others’ use of the Service.;
 xi. You will not alter or tamper with any information or materials on or associated with the Service. Other than connecting to Company’s servers by http requests using a Web browser, You may not attempt to gain access to Company’s servers by any means – including, without limitation, by using administrator passwords or by masquerading as an administrator while using the Service or otherwise.
 c. You are solely responsible for up to date contact information to receive information from the Service. Company will not be liable for information sent to a device that is associated with Your outdated mobile phone number or email address. If You install any software or enable any service that stores information from the Service on any mobile device or computer, it is Your responsibility, prior to transfer of such device, to remove Your information or otherwise disable access to such software or service, in order to prevent unauthorized access to Your information or account. Company reserves the right to provide You with information relating to Your schedule and/or use of the Service, including emergency matters and messages from our suppliers regarding their respective services.
 d. You are solely responsible for any activity and content (including, without limitation, data, text, information, screen names, graphics, photos, profiles, audio and video clips, and links to third-party content) that is displayed, published, uploaded or posted through Your user account (collectively, “User Content”). If You have reason to believe that Your account is no longer secure (e.g., loss, theft or unauthorized disclosure or use of Your access information or computer or mobile device used to access the Service), You are responsible for changing the affected access information.
 e. You acknowledge that Company has not reviewed and does not endorse the content of all sites linked to from this Service and is not responsible for the content or actions of any other sites linked to or from this Service, including but not limited to your authentication via a third party social networking site such as Facebook, Google +, or Linked In, and Your use of such sites via the Service. Your linking to any other service or site is at Your sole risk. By linking this Service to another service or site, You expressly agree to the disclosure of User Content permitted by or required to support such linking.
 f. In order for You to access travel itinerary and related data, You authorize Company to obtain such data on Your behalf and You represent that You have the right to control and access the data which You request and access through the Service.
 g. In order for You to receive information, including advertisements, regarding additional products or services originating from Company or third parties, You authorize Company to send You promotional e-mails, messages, and offers through the Service. You acknowledge that Company is not responsible for the content of such advertisements, e-mails, messages and offers.

 </Text>

<Text style={{ padding: 20 }}>
  
 3. Intellectual Property and Data
 a. Company retains all rights and ownership to copyright, trademark, trade secret and any other intellectual property rights in the Service and any derivative works thereof. All content of the Service (except User Content as defined below), including but not limited to designs, text, graphics, pictures, video, information, applications, software, music, sound and other files, their selection and arrangement, and its “look and feel” (the “Service Content”), are the proprietary property of Company or its licensors with all rights reserved. No Service Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without Vendor’s prior written permission. You do not acquire any rights in the Service or the Service Content, other than those rights expressly granted under this Agreement.
 b. We do not assert ownership of the photos, profiles, (Your User Content.) When You post User Content, You authorize and direct us to disclose User Content as necessary to provide the Service and make such copies thereof as we deem necessary in order to facilitate transmission, posting and storage of the User Content on the Services. By posting User Content, in connection with any part of the Service, You automatically grant and You represent and warrant that You have a right to grant to Company, and all other users an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with right to freely sublicense) to use, copy, modify, publicly perform, publicly display, reformat, translate, syndicate, republish, excerpt (in whole or in part) and distribute such User Content for any purpose, commercial, advertising or otherwise, on or in connection with the Service or the promotion thereof, and to prepare derivative works of, or incorporate into other works such User Content. You may remove Your User Content from the Service at any time, but You acknowledge that Company may not be able to and has no obligation to restrict any use by any other person, including other users, and the license You have granted remains in effect. The use of User Content by Company is subject to applicable laws and Vendor’s data privacy policy available at www.Rosnet.com/privacy_policy or its successor site.
 c. If You provide Company with feedback, suggestions, testimonials, comments, ideas, ratings, reviews, bug reports, or any similar or related information (“Feedback”), You agree that (a) any and all right, title and interest to such Feedback will become the exclusive property of Company, (b) Company will be able to use and share such Feedback without Your consent, only if Company does not use Your first and last name (c) If You give prior consent, Company will be able to use and share such Feedback, while including Your first and last name (d) Company will not be responsible for providing You with any compensation whatsoever regarding the Feedback, and (e) Company may already have contemplated or be contemplating the same or similar ideas as Your Feedback. If You do not agree with these terms regarding Feedback, or want to maintain ownership of any intellectual property contained in any specific Feedback, Your sole option and recourse is to not submit such specific Feedback to Company.
 d. We respect the intellectual property rights of others and we prohibit users from uploading, posting or otherwise transmitting on the Company/Rosnet website or Service, any materials that violate another party’s intellectual property rights. The Digital Millennium Copyright Act of 1998 (as amended, the “DMCA”) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If You believe in good faith that materials hosted by Company infringe Your copyright, You may send us a notice requesting that the material be removed, or access to it blocked. Notices must meet the current statutory requirements imposed by the DMCA; see 17 U.S.C 512 for details. Notices with respect to the Site should be sent to Rosnet, 8500 NW River Park Dr, Suite 342, Parkville, MO 64152, Attn: General Counsel. You should consult Your legal advisor before filing a notice. Note, there can be penalties for false claims under the DMCA.
 4. Fees and Optional Services
 a. The basic Service is provided to You at no additional charge from Company. You are solely responsible for any fees or charges incurred to access the Service through an Internet access provider or other third party, including without limitation charges incurred to receive SMS messages or other mobile access, which may be billed to You or deducted from Your prepaid balance by Your mobile provider. You agree that Company is not liable in any way for any third party charges. Company reserves the right to offer these Service and other services (Optional Service(s)) for a subscription or other fee. Any use of Optional Services will be governed by these terms and any additional terms specific to the applicable Optional Service(s) used by You.
 b. Unless Company states in writing otherwise, all fees and charges for the Service are nonrefundable.
 5. Disclaimers and Limitation of Liability
 a. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS OR IMPLIED, OF ANY KIND WITH RESPECT TO THE SERVICES, INCLUDING BUT NOT LIMITED TO THE ACCURACY OR COMPLETENESS OF ANY INFORMATION CONTAINED THEREIN OR PROVIDED BY OR THROUGH THE SERVICE.. THE SERVICE IS PROVIDED “AS IS” WITH NO WARRANTY. YOU AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, VENDOR EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, WITH RESPECT TO THE SERVICES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, ACCURACY, TITLE AND NON-INFRINGEMENT, AND ANY WARRANTIES THAT MAY ARISE OUT OF COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE OF TRADE. COMPANY DOES NOT WARRANT THAT THE SERVICE WILL OPERATE IN COMBINATION WITH HARDWARE, SOFTWARE, SYSTEMS OR DATA NOT PROVIDED BY COMPANY OR THAT THE OPERATION OF THE SERVICE WILL BE UNINTERRUPTED OR FREE OF VIRUSES OR ERRORS.
 b. THE SERVICE INCLUDES INFORMATION PROVIDED FROM A VARIETY OF SOURCES AND THIRD PARTIES. THE PROVIDERS OF SUCH INFORMATION AND/OR OTHER SERVICES ON Rosnet ARE INDEPENDENT CONTRACTORS AND NOT AGENTS OR EMPLOYEES OF COMPANY OR ITS AFFILIATES. COMPANY’S DISPLAY OF SUCH INFORMATION DOES NOT IN ANY WAY IMPLY, SUGGEST, OR CONSTITUTE ANY SPONSORSHIP OR APPROVAL BY COMPANY OF SUCH INFORMATION OR ITS PROVIDERS. YOU AGREE THAT COMPANY IS IN NO WAY RESPONSIBLE FOR THE ACCURACY, TIMELINESS, OR COMPLETENESS OF INFORMATION IT MAY OBTAIN FROM THESE THIRD PARTY SOURCES. YOUR INTERACTION WITH SUCH PROVIDERS IS AT YOUR OWN RISK. COMPANY AND ITS AFFILIATES WILL HAVE NO LIABILITY FOR THE ACTS, ERRORS, OMISSIONS, REPRESENTATIONS, WARRANTIES, BREACHES OR NEGLIGENCE OF ANY SUCH PROVIDERS OR FOR ANY PERSONAL INJURIES, DEATH, PROPERTY DAMAGE, OR OTHER DAMAGES OR EXPENSES RESULTING THEREFROM. COMPANY AND ITS AFFILIATES HAVE NO LIABILITY AND WILL MAKE NO REFUND IN THE EVENT OF ANY DELAY, CANCELLATION, OVERBOOKING, STRIKE, FORCE MAJEURE, OR OTHER CAUSES BEYOND OUR DIRECT CONTROL.
 c. Limitation of Liability. IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, BUSINESS, SAVINGS, DATA, USE OR COST OF SUBSTITUTE PROCUREMENT, INCURRED BY EITHER PARTY OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, EVEN IF THE OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR IF SUCH DAMAGES ARE FORESEEABLE. IN NO EVENT WILL COMPANY’S LIABILITY FOR DAMAGES HEREUNDER EXCEED THE LESSER OF (I) AMOUNTS ACTUALLY PAID BY YOU TO COMPANY FOR THE SERVICE OR US$500. THE PARTIES ACKNOWLEDGE THAT THE LIMITATIONS OF LIABILITY IN THIS SECTION AND IN THE OTHER PROVISIONS OF THIS AGREEMENT AND THE ALLOCATION OF RISK HEREIN ARE AN ESSENTIAL ELEMENT OF THIS TRANSACTION BETWEEN THE PARTIES, WITHOUT WHICH COMPANY WOULD NOT HAVE ENTERED INTO THIS AGREEMENT. COMPANY’S PRICING REFLECTS THIS ALLOCATION OF RISK AND THE LIMITATION OF LIABILITY SPECIFIED HEREIN. SOME STATES/COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND/OR EXCLUSION OR LIMITATION OF LIABILITY MAY NOT APPLY TO YOU.
 6. Resolution of Disputes
 a. Except for resolution of disputes concerning Rosnet’s Safe Harbor Program which is outlined in Rosnet’s Privacy Statement, these Terms shall govern any disputes between You and Us. If a dispute does arise between You and Us, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, You and We agree that we shall resolve any action, claim or controversy at law or equity (a “Claim”) that arises out of your use of the Services, these Terms, or the parties’ relationship in connection with the Services or these Terms in accordance with one of the subsections below or as otherwise mutually agreed by the parties in writing. Before resorting to these alternatives, we strongly encourage you to first contact us directly to seek a resolution by contacting customer service, since most customer concerns can be resolved quickly and satisfactorily in this manner.
 b. Submission to Jurisdiction in Missouri. You agree that unless otherwise mutually agreed by the parties in writing or as described in the “Mandatory Arbitration” subsection below, any Claims shall be brought in the state or federal courts located in Platte County, the State of Missouri, United States of America. Unless otherwise prohibited by applicable law, any Claim must be brought within two (2) years from the date on which such Claim arose or accrued.
 c. Mandatory Arbitration. Any Claim where the total amount in controversy is less than US$10,000, shall be resolved via binding arbitration initiated through the American Arbitration Association (“AAA”). The arbitration will be governed by the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by this Agreement, and will be administered by the AAA. The AAA Rules are available online at www.adr.org or by calling the AAA at 1-800-778-7879. AAA and the parties must comply with the following rules: (a) if either party requests an in-person hearing the process shall be governed by subsection (c) below, otherwise, the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (b) the arbitration shall be conducted by an arbitrator in Tarrant County, Texas who is approved or otherwise affiliated with the AAA; (c) if either party requests an in-person hearing, the arbitrator shall decide whether a hearing is necessary or whether the arbitration shall proceed as described in subsection (a) above. If the arbitrator deems that a hearing is necessary, the hearing shall occur at a mutually agreed upon location, or, if the parties are unable to agree on a location, at a location that is reasonably convenient to You and is selected by the arbitrator. Either party may elect to participate in an in-person hearing by phone, unless the arbitrator decides otherwise (d) the arbitrator may award injunctive or declaratory relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim; (e) unless otherwise mutually agreed by the parties in writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding; and (f) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. If subparagraph (e) above is found to be unenforceable, then the entirety of this Mandatory Arbitration provision shall be null and void. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION WITH RESPECT TO THE CLAIMS COVERED BY THIS MANDATORY ARBITRATION PROVISION. Notwithstanding the foregoing, either party may bring an individual action in small claims court in Platte County, Missouri.
 d. Improperly Filed Claims. All Claims You bring against Us must be resolved in accordance with this “Resolution of Disputes” section. All Claims filed or brought contrary to this “Resolution of Disputes” section shall be considered improperly filed and void. Should you file a Claim contrary to this “Resolution of Disputes” section, we may recover attorneys’ fees and costs up to $1,000, provided that we have notified you in writing of the improperly filed Claim, and you have failed to promptly withdraw the Claim.
 e. Attorney’s Fees. If we take any action to enforce these Terms, and such Claim is not resolved pursuant to the “Mandatory Arbitration” subsection above, we will be entitled to recover from you, and you agree to pay, all reasonable attorney’s fees and any costs of litigation, in addition to any other relief, at law or in equity, to which we may be entitled. Moreover, you agree that we may debit your credit or debit card or charge you for any such amounts.
 f. Injunctive Relief. You acknowledge that a violation or attempted violation of any of these Terms will cause such damage to us as will be irreparable, the exact amount of which would be impossible or difficult to ascertain and for which there will be no adequate remedy at law. Accordingly, you agree that we shall be entitled as a matter of right to seek an injunction from any court of competent jurisdiction, restraining such violation or attempted violation of these Terms by you, or your affiliates, partners, or agents, without having to post a bond or other security.
 7. Termination. This Agreement is effective until terminated by You or Company. Company may terminate this Agreement at any time upon (i) Your breach of any of the provisions hereof or (ii) upon electronic notice to You. Upon termination of this Agreement, You will cease all use of the Service.
 7. General Terms
 a. Applicable Law. This Agreement and all matters arising out of or relating thereto, except as governed by federal law, will be governed by the laws of the State of Missouri without giving effect to any choice of law rule. This Agreement will not be governed by the United Nations Convention on Contracts for the International Sales of Goods, the application of which is expressly excluded. Any controversy, claim or dispute between the parties arising out of this Agreement may be tried solely in a state or federal court for Platte County, Missouri, and the parties hereby irrevocably consent to the jurisdiction and venue of such courts. Before resorting to this alternative, we strongly encourage You to first contact us directly to seek a resolution.
 b. Severability and Waiver. If any provision of this Agreement is held to be unenforceable, such provision will be enforced to the extent possible consistent with the stated intention of the parties, or, if incapable of such enforcement, will be deemed to be severed and deleted from this Agreement, while the remainder of this Agreement will continue in full force and effect. The waiver by either party of any default or breach of this Agreement will not constitute a waiver of any other or subsequent default or breach.
 c. No Assignment. You may not assign or otherwise dispose of this Agreement or any rights or obligations under this Agreement without the prior written consent of Vendor. Any purported assignment by You will be null and void. Subject to the foregoing, this Agreement will be binding upon and will inure to the benefit of the parties and their respective successors and assigns.
 d. Export Administration. You will comply fully with all relevant export laws and regulations of the United States, including, without limitation, the U.S. Export Administration Regulations (collectively “Export Controls”). Without limiting the generality of the foregoing, You will not, and You will require Your representatives not to, export, direct or transfer the Program, or any direct product thereof, to any destination, person or entity restricted or prohibited by the Export Controls.
 e. Entire Agreement. This Agreement constitutes the entire agreement between the parties and supersedes all prior or contemporaneous agreements or representations, written or oral, concerning the subject matter of this Agreement.
 f. Right to Modify. Company reserves the right to modify or replace this Agreement at any time and in Company’s sole discretion. Company will indicate at the top of this Agreement the date such document was last updated. Any changes will be effective immediately upon posting the revised version (or such later effective date as may be indicated at the top of the revised Agreement). It is Your responsibility to regularly check the Rosnet.com website to determine if there have been changes to this Agreement and to review such changes. Your continued use of the Service following the posting of any changes to the Agreement will mean Your acceptance of any such changes. If You do not agree to the changes, You must stop using the Service.

        </Text>

        </ScrollView>

      </View>
    );

  }
}


//make this component available to the app
export default Terms;