# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rosnet' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  pod 'AppCenter/Push', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rosnet

  

  platform :ios, '9.0'
  target 'RosnetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Rosnet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rosnet-tvOS

  target 'Rosnet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
