

POST https://aag.rosnetqa.com/api/ManagerAppAuth/aag.rosnetdev.com/api/ManagerAppAuth/AuthenticateUser?userName=vchikkala@rosnet.com&password=Rosnet@123

{
    "userName" : "vchikkala@rosnet.com",
    
}

###

{
    "userName": "dywayne.johnson",
    "password": "***"
}

POST https://dashboard.rosnetqa.com/api/ManagerAppAuth/AuthenticateUser?userName=dywayne.johnson&password=gorosnet1$

###

POST https://aag.rosnetqa.com/Signon/PasswordChange?__dt=1549485051016&userId=29269&password=Rosnet@123
Content-Type: application/application/json

###
 
GET https://aag.rosnetdev.com/Signon/PasswordChangeExec?__dt=1549485051016&userId=29269&password=Rosnet@123
//content-type: application/json


###
POST https://aag.rosnetdev.com/SignOn/PasswordChangeExec
content-type: application/json

{
"userId": "29269",
"password": "Rosnet@123"
 
}

