

### trying to connect to my windows pc....
POST http://dashboard.dywaynes-pc.com/api/ManagerAppAuth/Login
Content-Type: application/json

{
    "userName" : "dywayne.johnson",
    "password": "gorosnet1$"
    
}

###



POST https://dashboard.rosnetqa.com/api/ManagerAppAuth/Login
Content-Type: application/json

{
    "userName" : "dywayne.johnson",
    "password": "gorosnet1$"
    
}

###


{
    "userName": "dywayne.johnson",
    "password": "***"
}



POST https://aag.rosnetqa.com/Signon/PasswordChange?__dt=1549485051016&userId=29269&password=Rosnet@123
Content-Type: application/json

###
 
GET https://aag.rosnetdev.com/Signon/PasswordChangeExec?__dt=1549485051016&userId=29269&password=Rosnet@123
//content-type: application/json


###
POST https://aag.rosnetdev.com/SignOn/PasswordChangeExec
content-type: application/json

{
"userId": "29269",
"password": "Rosnet@123"
 
}

###
POST https://aag.rosnetdev.com/SignOn/RetrievePassword?Email=vchikkala@rosnet.com&ClientCode=Doherty
content-type: application/json

###

{
"userId": "vchikkala@rosnet.com",
//"password": "Rosnet@123"
"ClientCode" : "AAG"
 
}



