


GET http://876ddea7.ngrok.io/api/ManagerAppMenu
Cookie: rememberme=dywayne.johnson; clientCode=aag; rosnetToken=91ebce15-5a52-4fe3-9291-a281ec76f167

###

GET https://aag.rosnetqa.com/api/ManagerAppMenu
Cookie: rememberme=dywayne.johnson; clientCode=aag; rosnetToken=8390bd37-dc40-4b35-b239-326dceea6a3a


###

GET https://aag.rosnetqa.com/api/ManagerAppMenu
Cookie: rememberme=dywayne.johnson; clientCode=aag; rosnetToken=03a425e1-56fe-4dd2-96d6-bfb2c96e2dda