


GET http://876ddea7.ngrok.io/api/ManagerAppModule/MobileNestedV1
Cookie: rememberme=dywayne.johnson; clientCode=aag; rosnetToken=91ebce15-5a52-4fe3-9291-a281ec76f167

###

GET https://aag.rosnetdev.com/WebFocus/Dashboard/847C5BE8-3B46-497D-B819-E8F78738A13B"
Cookie: "rememberme=vchikkala@rosnet.com; clientCode=aag; rosnetToken=ec626161-16e9-47a7-bcfb-8fcb56bb7812"
