
### 8E595DDE-F76A-40B5-8605-23A9A5E94BBF	99211152-5B93-4F6E-9CB2-3D3B42B9A275	2	13636	2018-08-09 10:54:00

### Send to all users

### iOS App Secret: f5d79277-b1c1-430c-bc9b-ef82bd9999aa

POST https://appcenter.ms/api/v0.1/apps/Rosnet/iOS-Rosnet/push/notifications
content-type: application/json
X-API-Token: 30b871cf9ae2c7d3aa1570815c4bff165b95cce4

{
 "notification_content" : {
  "name" : "Rosnet - Broadcast to All Users",
  "title" : "Dywayne & Viswa Test - Push Using App Center API",
  "body" : "Please let me know if you get this.",
  "custom_data" : {"key1" : "val1", "key2" : "val2"}
  }
}

### Send to specific users by device ID
### Dywayne's App Center Install ID: CD4F05F3-A656-46BE-9240-40D62E50553E

POST https://appcenter.ms/api/v0.1/apps/Rosnet/iOS-Rosnet/push/notifications
content-type: application/json
X-API-Token: 30b871cf9ae2c7d3aa1570815c4bff165b95cce4

{
    "notification_content" : {
        "name" : "Rosnet",
        "title" : "Dywayne Test - Push Using App Center API",
        "body" : "Please let me know if you get this.",
        "custom_data" : {"key1" : "val1", "key2" : "val2"}
    },
    "notification_target" : {
        "type" : "devices_target",
        "devices" : ["EDA9F233-D8FA-4BF7-B47E-CD5A61214094"]
    }
}

###

POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AIzaSyD4P1ipSHCgI4JIOSGIdaSP5Gbr21rWSWg

{ "data": {
    "score": "5x1",
    "time": "15:10"
  },
  "registration_ids" : ["d2eSXokIiAA:APA91bEqN0Z_--SiNu7wDVZ-1AnTHel3FHvuoNx-LbO1nNnDCjLNXOGBql_qyxgFe0ZWSFoDtuocr4MwHZwnBhKAvQZPeRsY2ww4EpaiRzTKURyL2qFid1tCFEjxffgpXFMpYyZ2gLlQ","dg8ugugSZkw:APA91bEZHvBN43PvGhdEsw-g4aVWd2QXj4fGVQh1yk0H_tfNDbijvJpflfV8cUi7ci_D7WM9q3REtMaLde8usd_hRP3toVKAQcTj_dEDH6PMLffrQm-vqiLcU61aePqhpqQd60NpedCs"],
  "notification": {
    "title": "Viswa is Testing ios",
    "text": "Let Viswa know you got it..He'll be very happy :-)"
      }
}

###

POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AIzaSyD4P1ipSHCgI4JIOSGIdaSP5Gbr21rWSWg

{ "data": {
    "client": "AAG"
  },
  "to" : "d8-5Dnvaj9A:APA91bEO5otMbXiIq98Ax_8abG-ahk5VZHWn_aJoDXJujGzi6kxxcldxNRU72iQPo6KW96RoAzum58SAIqW2rGSN7pZWKGVnBAF0NVYdxItJvOk0T2uOsVmjKaEMMFGI56hsW4qafCuU",
  "notification": {
    "title": "Test from http",
    "text": "Succes!!!",
    "badge" : 1 
  }
}