

GET https://aag.rosnetqa.com/api/ManagerAppSite/StaffList?location=2020011
Content-Type: application/json
managerAppToken: 24340d0f-1c25-43c8-8ddb-c68d2476ce52

###


GET https://aag.rosnetqa.com/api/ManagerAppSite/SecuritySettings
Content-Type: application/json
managerAppToken: 24340d0f-1c25-43c8-8ddb-c68d2476ce52