POST http://aag.rosnetqa.com/api/ManagerAppZendesk/ReportIssue
Content-Type: application/json
managerAppToken: 63664408-17ec-457e-8af9-eebd7aad4fa1

{
    "subject" : "Test by Dywayne",
    "description": "Test by Dywayne. Please disregard.",
    "location": "Location in the Rosnet App", 
    "browser": "Browser is the Rosnet App",
    "value": null
}


### GET USER REQUESTS ### 



GET https://aag.rosnetqa.com/api/ManagerAppZendesk/Requests?email=djohnson@rosnet.com&count=1
content-type: application/json
managerAppToken: 63664408-17ec-457e-8af9-eebd7aad4fa1


### CREATE USER ### 

POST https://aag.rosnetqa.com/api/ManagerAppZendesk/AddUser
Content-Type: application/json
managerAppToken: 52d54eb2-c56e-44ea-97e2-92642651fb40

{
    "rosnet_user_id" : 1234, // this is the ExternalID for Zendesk
    "email": "testuser2@rosnet.com", 
    "name": "Test User2",
    "location": 0
}


### DELETE USER ###

DELETE https://aag.rosnetqa.com/api/ManagerAppZendesk/DeleteUser?zendesk_id=380579411772
content-type: application/json
managerAppToken: 52d54eb2-c56e-44ea-97e2-92642651fb40


### SEARCH USERS BY EMAIL ###

GET https://aag.rosnetqa.com/api/ManagerAppZendesk/SearchUsersByEmail?email=dj-test-002@rosnet.com
content-type: application/json
managerAppToken: 85fd2345-7381-49f8-90d8-a6985304e504

### SEARCH USERS BY External ID ###

GET https://aag.rosnetqa.com/api/ManagerAppZendesk/SearchUsersByRosnetExternalID?rosnet_user_id=999999002
content-type: application/json
managerAppToken: 85fd2345-7381-49f8-90d8-a6985304e504
