
POST https://aag.rosnetqa.com/api/ManagerAppUser/UpdateProfile
Content-Type: application/json
managerAppToken: 2b8bc9d5-7e6e-4b06-9269-cdc22b7eb2ab

{
    "jobTitle": "Software Engineer",
    "email": ""
}


